# Generated by Django 2.2.4 on 2019-08-25 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoLesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
